/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgencyRouteRouteImport } from './routes/agency/route'
import { Route as ContractorRouteRouteImport } from './routes/contractor/route'
import { Route as AgencyIndexRouteImport } from './routes/agency/index'
import { Route as AgencyContractorsRouteImport } from './routes/agency/contractors'
import { Route as AgencyDashboardRouteImport } from './routes/agency/dashboard'
import { Route as AgencyDumpPointsRouteImport } from './routes/agency/dump-points'
import { Route as AgencyManageDumpPointsRouteImport } from './routes/agency/manage-dump-points'
import { Route as AgencyManageSitesRouteImport } from './routes/agency/manage-sites'
import { Route as AgencyReportersRouteImport } from './routes/agency/reporters'
import { Route as AgencySignInRouteImport } from './routes/agency/sign-in'
import { Route as ContractorIndexRouteImport } from './routes/contractor/index'
import { Route as ContractorAccountRouteImport } from './routes/contractor/account'
import { Route as ContractorHistoryRouteImport } from './routes/contractor/history'
import { Route as ContractorSignInRouteImport } from './routes/contractor/sign-in'
import { Route as ContractorSitesRouteImport } from './routes/contractor/sites'
import { Route as AgencySitesSiteIdRouteImport } from './routes/agency/sites.$siteId'
import { Route as ContractorSitesSiteIdRouteImport } from './routes/contractor/sites.$siteId'
import { Route as AgencySitesSiteIdVisitsVisitIdRouteImport } from './routes/agency/sites.$siteId.visits.$visitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRouteRoute = AgencyRouteRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorRouteRoute = ContractorRouteRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyIndexRoute = AgencyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyContractorsRoute = AgencyContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyDashboardRoute = AgencyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyDumpPointsRoute = AgencyDumpPointsRouteImport.update({
  id: '/dump-points',
  path: '/dump-points',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyManageDumpPointsRoute = AgencyManageDumpPointsRouteImport.update({
  id: '/manage-dump-points',
  path: '/manage-dump-points',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyManageSitesRoute = AgencyManageSitesRouteImport.update({
  id: '/manage-sites',
  path: '/manage-sites',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyReportersRoute = AgencyReportersRouteImport.update({
  id: '/reporters',
  path: '/reporters',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencySignInRoute = AgencySignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const ContractorIndexRoute = ContractorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorAccountRoute = ContractorAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorHistoryRoute = ContractorHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorSignInRoute = ContractorSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorSitesRoute = ContractorSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const AgencySitesSiteIdRoute = AgencySitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const ContractorSitesSiteIdRoute = ContractorSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => ContractorSitesRoute,
} as any)
const AgencySitesSiteIdVisitsVisitIdRoute =
  AgencySitesSiteIdVisitsVisitIdRouteImport.update({
    id: '/visits/$visitId',
    path: '/visits/$visitId',
    getParentRoute: () => AgencySitesSiteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRouteRouteWithChildren
  '/contractor': typeof ContractorRouteRouteWithChildren
  '/agency/contractors': typeof AgencyContractorsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/dump-points': typeof AgencyDumpPointsRoute
  '/agency/manage-dump-points': typeof AgencyManageDumpPointsRoute
  '/agency/manage-sites': typeof AgencyManageSitesRoute
  '/agency/reporters': typeof AgencyReportersRoute
  '/agency/sign-in': typeof AgencySignInRoute
  '/contractor/account': typeof ContractorAccountRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/sign-in': typeof ContractorSignInRoute
  '/contractor/sites': typeof ContractorSitesRouteWithChildren
  '/agency/': typeof AgencyIndexRoute
  '/contractor/': typeof ContractorIndexRoute
  '/agency/sites/$siteId': typeof AgencySitesSiteIdRouteWithChildren
  '/contractor/sites/$siteId': typeof ContractorSitesSiteIdRoute
  '/agency/sites/$siteId/visits/$visitId': typeof AgencySitesSiteIdVisitsVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency/contractors': typeof AgencyContractorsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/dump-points': typeof AgencyDumpPointsRoute
  '/agency/manage-dump-points': typeof AgencyManageDumpPointsRoute
  '/agency/manage-sites': typeof AgencyManageSitesRoute
  '/agency/reporters': typeof AgencyReportersRoute
  '/agency/sign-in': typeof AgencySignInRoute
  '/contractor/account': typeof ContractorAccountRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/sign-in': typeof ContractorSignInRoute
  '/contractor/sites': typeof ContractorSitesRouteWithChildren
  '/agency': typeof AgencyIndexRoute
  '/contractor': typeof ContractorIndexRoute
  '/agency/sites/$siteId': typeof AgencySitesSiteIdRouteWithChildren
  '/contractor/sites/$siteId': typeof ContractorSitesSiteIdRoute
  '/agency/sites/$siteId/visits/$visitId': typeof AgencySitesSiteIdVisitsVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency': typeof AgencyRouteRouteWithChildren
  '/contractor': typeof ContractorRouteRouteWithChildren
  '/agency/contractors': typeof AgencyContractorsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/dump-points': typeof AgencyDumpPointsRoute
  '/agency/manage-dump-points': typeof AgencyManageDumpPointsRoute
  '/agency/manage-sites': typeof AgencyManageSitesRoute
  '/agency/reporters': typeof AgencyReportersRoute
  '/agency/sign-in': typeof AgencySignInRoute
  '/contractor/account': typeof ContractorAccountRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/sign-in': typeof ContractorSignInRoute
  '/contractor/sites': typeof ContractorSitesRouteWithChildren
  '/agency/': typeof AgencyIndexRoute
  '/contractor/': typeof ContractorIndexRoute
  '/agency/sites/$siteId': typeof AgencySitesSiteIdRouteWithChildren
  '/contractor/sites/$siteId': typeof ContractorSitesSiteIdRoute
  '/agency/sites/$siteId/visits/$visitId': typeof AgencySitesSiteIdVisitsVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency'
    | '/contractor'
    | '/agency/contractors'
    | '/agency/dashboard'
    | '/agency/dump-points'
    | '/agency/manage-dump-points'
    | '/agency/manage-sites'
    | '/agency/reporters'
    | '/agency/sign-in'
    | '/contractor/account'
    | '/contractor/history'
    | '/contractor/sign-in'
    | '/contractor/sites'
    | '/agency/'
    | '/contractor/'
    | '/agency/sites/$siteId'
    | '/contractor/sites/$siteId'
    | '/agency/sites/$siteId/visits/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency/contractors'
    | '/agency/dashboard'
    | '/agency/dump-points'
    | '/agency/manage-dump-points'
    | '/agency/manage-sites'
    | '/agency/reporters'
    | '/agency/sign-in'
    | '/contractor/account'
    | '/contractor/history'
    | '/contractor/sign-in'
    | '/contractor/sites'
    | '/agency'
    | '/contractor'
    | '/agency/sites/$siteId'
    | '/contractor/sites/$siteId'
    | '/agency/sites/$siteId/visits/$visitId'
  id:
    | '__root__'
    | '/'
    | '/agency'
    | '/contractor'
    | '/agency/contractors'
    | '/agency/dashboard'
    | '/agency/dump-points'
    | '/agency/manage-dump-points'
    | '/agency/manage-sites'
    | '/agency/reporters'
    | '/agency/sign-in'
    | '/contractor/account'
    | '/contractor/history'
    | '/contractor/sign-in'
    | '/contractor/sites'
    | '/agency/'
    | '/contractor/'
    | '/agency/sites/$siteId'
    | '/contractor/sites/$siteId'
    | '/agency/sites/$siteId/visits/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyRouteRoute: typeof AgencyRouteRouteWithChildren
  ContractorRouteRoute: typeof ContractorRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor': {
      id: '/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof ContractorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/': {
      id: '/agency/'
      path: '/'
      fullPath: '/agency/'
      preLoaderRoute: typeof AgencyIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/contractors': {
      id: '/agency/contractors'
      path: '/contractors'
      fullPath: '/agency/contractors'
      preLoaderRoute: typeof AgencyContractorsRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/dashboard': {
      id: '/agency/dashboard'
      path: '/dashboard'
      fullPath: '/agency/dashboard'
      preLoaderRoute: typeof AgencyDashboardRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/dump-points': {
      id: '/agency/dump-points'
      path: '/dump-points'
      fullPath: '/agency/dump-points'
      preLoaderRoute: typeof AgencyDumpPointsRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/manage-dump-points': {
      id: '/agency/manage-dump-points'
      path: '/manage-dump-points'
      fullPath: '/agency/manage-dump-points'
      preLoaderRoute: typeof AgencyManageDumpPointsRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/manage-sites': {
      id: '/agency/manage-sites'
      path: '/manage-sites'
      fullPath: '/agency/manage-sites'
      preLoaderRoute: typeof AgencyManageSitesRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/reporters': {
      id: '/agency/reporters'
      path: '/reporters'
      fullPath: '/agency/reporters'
      preLoaderRoute: typeof AgencyReportersRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/sign-in': {
      id: '/agency/sign-in'
      path: '/sign-in'
      fullPath: '/agency/sign-in'
      preLoaderRoute: typeof AgencySignInRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/contractor/': {
      id: '/contractor/'
      path: '/'
      fullPath: '/contractor/'
      preLoaderRoute: typeof ContractorIndexRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/account': {
      id: '/contractor/account'
      path: '/account'
      fullPath: '/contractor/account'
      preLoaderRoute: typeof ContractorAccountRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/history': {
      id: '/contractor/history'
      path: '/history'
      fullPath: '/contractor/history'
      preLoaderRoute: typeof ContractorHistoryRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/sign-in': {
      id: '/contractor/sign-in'
      path: '/sign-in'
      fullPath: '/contractor/sign-in'
      preLoaderRoute: typeof ContractorSignInRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/sites': {
      id: '/contractor/sites'
      path: '/sites'
      fullPath: '/contractor/sites'
      preLoaderRoute: typeof ContractorSitesRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/agency/sites/$siteId': {
      id: '/agency/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/agency/sites/$siteId'
      preLoaderRoute: typeof AgencySitesSiteIdRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/contractor/sites/$siteId': {
      id: '/contractor/sites/$siteId'
      path: '/$siteId'
      fullPath: '/contractor/sites/$siteId'
      preLoaderRoute: typeof ContractorSitesSiteIdRouteImport
      parentRoute: typeof ContractorSitesRoute
    }
    '/agency/sites/$siteId/visits/$visitId': {
      id: '/agency/sites/$siteId/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/agency/sites/$siteId/visits/$visitId'
      preLoaderRoute: typeof AgencySitesSiteIdVisitsVisitIdRouteImport
      parentRoute: typeof AgencySitesSiteIdRoute
    }
  }
}

interface AgencySitesSiteIdRouteChildren {
  AgencySitesSiteIdVisitsVisitIdRoute: typeof AgencySitesSiteIdVisitsVisitIdRoute
}

const AgencySitesSiteIdRouteChildren: AgencySitesSiteIdRouteChildren = {
  AgencySitesSiteIdVisitsVisitIdRoute: AgencySitesSiteIdVisitsVisitIdRoute,
}

const AgencySitesSiteIdRouteWithChildren =
  AgencySitesSiteIdRoute._addFileChildren(AgencySitesSiteIdRouteChildren)

interface AgencyRouteRouteChildren {
  AgencyContractorsRoute: typeof AgencyContractorsRoute
  AgencyDashboardRoute: typeof AgencyDashboardRoute
  AgencyDumpPointsRoute: typeof AgencyDumpPointsRoute
  AgencyManageDumpPointsRoute: typeof AgencyManageDumpPointsRoute
  AgencyManageSitesRoute: typeof AgencyManageSitesRoute
  AgencyReportersRoute: typeof AgencyReportersRoute
  AgencySignInRoute: typeof AgencySignInRoute
  AgencyIndexRoute: typeof AgencyIndexRoute
  AgencySitesSiteIdRoute: typeof AgencySitesSiteIdRouteWithChildren
}

const AgencyRouteRouteChildren: AgencyRouteRouteChildren = {
  AgencyContractorsRoute: AgencyContractorsRoute,
  AgencyDashboardRoute: AgencyDashboardRoute,
  AgencyDumpPointsRoute: AgencyDumpPointsRoute,
  AgencyManageDumpPointsRoute: AgencyManageDumpPointsRoute,
  AgencyManageSitesRoute: AgencyManageSitesRoute,
  AgencyReportersRoute: AgencyReportersRoute,
  AgencySignInRoute: AgencySignInRoute,
  AgencyIndexRoute: AgencyIndexRoute,
  AgencySitesSiteIdRoute: AgencySitesSiteIdRouteWithChildren,
}

const AgencyRouteRouteWithChildren = AgencyRouteRoute._addFileChildren(
  AgencyRouteRouteChildren,
)

interface ContractorSitesRouteChildren {
  ContractorSitesSiteIdRoute: typeof ContractorSitesSiteIdRoute
}

const ContractorSitesRouteChildren: ContractorSitesRouteChildren = {
  ContractorSitesSiteIdRoute: ContractorSitesSiteIdRoute,
}

const ContractorSitesRouteWithChildren = ContractorSitesRoute._addFileChildren(
  ContractorSitesRouteChildren,
)

interface ContractorRouteRouteChildren {
  ContractorAccountRoute: typeof ContractorAccountRoute
  ContractorHistoryRoute: typeof ContractorHistoryRoute
  ContractorSignInRoute: typeof ContractorSignInRoute
  ContractorSitesRoute: typeof ContractorSitesRouteWithChildren
  ContractorIndexRoute: typeof ContractorIndexRoute
}

const ContractorRouteRouteChildren: ContractorRouteRouteChildren = {
  ContractorAccountRoute: ContractorAccountRoute,
  ContractorHistoryRoute: ContractorHistoryRoute,
  ContractorSignInRoute: ContractorSignInRoute,
  ContractorSitesRoute: ContractorSitesRouteWithChildren,
  ContractorIndexRoute: ContractorIndexRoute,
}

const ContractorRouteRouteWithChildren = ContractorRouteRoute._addFileChildren(
  ContractorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyRouteRoute: AgencyRouteRouteWithChildren,
  ContractorRouteRoute: ContractorRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
